image: python:3.7-alpine

test:
  stage: test
  script:
  - make test

pages:
  stage: deploy
  script:
  - apk add tk make build-base python-dev py-pip jpeg-dev zlib-dev musl-dev
  - export LIBRARY_PATH=/lib:/usr/lib
  - pip install --upgrade pip
  - pip install --upgrade pillow
  - pip -r requirements.txt
  - export PYTHONPATH="za_warudo"
  - pdoc3 --html -o public za_warudo --force
  artifacts:
    paths:
    - public
