image: python:3.7-alpine

test:
  stage: test
  script:
  - export PYTHONPATH="src"
  - python tests/TestListMethods.py

pages:
  stage: deploy
  script:
  - apk add tk
  - apk add build-base python-dev py-pip jpeg-dev zlib-dev musl-dev
  - export LIBRARY_PATH=/lib:/usr/lib
  - pip install --upgrade pip
  - pip install --upgrade pillow
  - pip3 install peewee
  - pip3 install tkcalendar
  - pip3 install ttkthemes
  - pip3 install ttkwidgets
  - pip3 install pdoc3
  - export PYTHONPATH="src"
  - pdoc3 --html -o public src --force
  artifacts:
    paths:
    - public
