image: python:3.7-alpine

test:
  stage: test
  script:
  - cp -R docs public
  only:
  - branches
  except:
  - master

pages:
  stage: deploy
  script:
  - cp -R docs public
  artifacts:
    paths:
    - public
  only:
  - master
