image: python:3.7-alpine

test:
  stage: test
  script:
  - export PYTHONPATH="src"
  - python tests/TestListMethods.py

pages:
  stage: deploy
  script:
  - apt-get install python-tk
  - pip3 install ttkthemes
  - pip3 install pdoc3
  - export PYTHONPATH="src"
  - pdoc3 --html -o public src --force
  artifacts:
    paths:
    - public
